version: '3'
services:
  service:
    build: .
    container_name: ack
    hostname: ack
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .env:/app/.env
networks:
  app-network:
    name: app-network
    driver: bridge